# -*- coding: utf-8 -*-

QUOTES = {
    "pt-br": [
        "Parabéns para a estrela da nossa empresa! Caro colega, é um prazer poder trabalhar com alguém tão talentoso e tão inspirador!",
        "Compartilhar o local de trabalho com você é um prazer, e mais do que um colega de trabalho, considero você um bom amigo. Feliz aniversário!",
        "É um orgulho trabalhar com um colega de trabalho como você que está sempre lá para ajudar e para apoiar aqueles que precisam. Tenha um feliz aniversário!",
        "É graças a colegas como você que o dia de trabalho corre mais rápido e sem darmos pelo tempo passar. Tenha o dia de aniversário feliz que você merece!",
        "As manhãs de segunda-feira custam menos por ter um colega divertido como você a animar o escritório. Feliz aniversário!",
        "Hoje é dia de festa no trabalho, pois o melhor dos colegas, e grande amigo também, está completando mais um ano de vida. Feliz aniversário, meu amigo!",
        "Você sabe que nunca foi só um colega de trabalho para mim, mas acima de tudo um…chato! Brincadeira, você é um grande amigo! Parabéns por mais um ano!",
        "Feliz Aniversário! Este é um dia grandioso, pois o milagre da vida se renova para você em mais um ciclo que começa hoje.",
        "Feliz Aniversário! Que a felicidade acompanhe sempre você, não só hoje, mas todos os dias da sua vida.",
        "Feliz aniversário! Que você faça desse dia, um momento muito especial, pois momentos como esses são para serem lembrados. Você é uma pessoa muito especial!",
        "Feliz Aniversário! Desejo que seu dia seja todo alegria e no seu coração não falte paz e amor.",
        "Que hoje toda felicidade do mundo se reúna para abraçar seu coração. Tenha um aniversário muito feliz!",
        "Parabéns por mais um ano de vida! Sorria, dance, pule de felicidade e celebre seu dia em grande estilo.",
        "Parabéns pelo aniversário, e que a felicidade caminhe ao seu lado a vida toda!",
        "Parabéns pelo seu dia! Que não falte paz, amor e alegria em todos os instantes de hoje.",
        "Desejo paz, alegria e muito amor a este seu dia. Feliz Aniversário!",
        "Curta este aniversário com alegria e receba mais um ano de vida com gratidão. Parabéns!",
        "Eu te desejo um aniversário repleto de emoções fortes, amizades verdadeiras e presentes inesquecíveis. Parabéns!",
        "Que todos os sonhos se realizem e nenhum presente seja dado sem alegria. Feliz Aniversário!",
        "Parabéns por mais um ano de vida lindo e memorável. Feliz Aniversário!",
        "Você é uma pessoa muito especial e não podia deixar de lhe desejar um aniversário muito feliz!",
        "Tenha um feliz aniversário e que este novo ciclo seja ainda mais incrível que o anterior!",
        "Ainda mal nos conhecemos, mas não podia deixar de lhe desejar um feliz aniversário. Que Deus abençoe seu dia!",
        "Desejo um feliz aniversário a uma pessoa incrível e extraordinária que eu tanto acarinho! Tenha um dia muito feliz!",
        "Que o seu dia seja verdadeiramente especial e que o ciclo que hoje inicia seja realmente incrível! Parabéns!",
        "Hoje é dia de festejar e comer todo o bolo que conseguir. Tenha um feliz aniversário!",
        "Feliz aniversário, linda amiga! Que o seu dia especial seja tão maravilhoso quanto você!",
        "Desejo um feliz aniversário à pessoa mais linda do mundo.",
        "Espero que curta muito o seu aniversário e esta frase de parabéns.",
        "Hoje que completa mais um ano de vida, quero simplesmente lhe desejar parabéns.",
        "Querido amigo, eu lhe desejo um aniversário incrível na companhia dos que mais ama. Parabéns!",
        "É hora de soprar vela e pedir um desejo. Feliz aniversário!",
        "Sabe o que dizem, meu amigo, quanto mais velho, mais sábio. Feliz aniversário!",
        "No seu aniversário, dou graças a Deus pela sua vida! Parabéns!"
    ],
    "en-us": [
        "Wishing you a great birthday and a memorable year. From all of us.",
        "Hoping your birthday brings you many happy reasons to celebrate!",
        "Wishing you the best on your birthday and everything good in the year ahead.",
        "Hope your day is filled with happiness.",
        "Wishing you a happy birthday and a wonderful year.",
        "Our whole team is wishing you the happiest of birthdays.",
        "Happy Birthday and all the best to you in the year to come!",
        "Wishing you a relaxing birthday and happiness in the year to come.",
        "The whole team wishes you the happiest of birthdays and a great year.",
        "May your birthday be the start of a year filled with good luck, good health and much happiness.",
        "Wishing you much happiness on your special day. Have an unforgettable birthday.",
        "Wishing you a day full of laughter and happiness and a year that brings you much success.",
        "May all life’s blessings be yours, on your birthday and always.",
        "Wishing you a happy birthday, a wonderful year and success in all you do.",
        "It seems such a great day to say we feel so lucky that you came our way! Happy Birthday to you! Make it grand!",
        "The warmest wishes to a great member of our team. May your special day be full of happiness, fun and cheer!",
        "With warm wishes for a very happy birthday and sincere thanks for your hard work throughout the year.",
        "Happy birthday to a wonderful person who means so many different things to our company!",
        "We wish you an amazing year that ends with accomplishing all the great goals that you have set!",
        "No one could do a better job than the job you do. We thank you for sticking with us! Enjoy your birthday!",
        "On behalf of the entire company I wish you a very happy birthday and send you my best wishes for much happiness in your life.",
        "It’s a pleasure to work with you and to wish you a happy birthday.",
        "You make work a lot less like work. Thanks for all you do!",
        "Thank you for all your hard work during the past year. Wishing you a happy birthday and a great year to come!",
        "We appreciate all of your hard work in the past year. Wishing you a happy and relaxing birthday!",
        "Best wishes on your birthday – may you have many, many more.",
        "Wishing you the happiest of birthdays.",
        "Best wishes for a fantastic person on [his/her] birthday.",
        "Happy Birthday! Today is a good day to spend some time with family, and some money on yourself.",
        "I hope you treat yourself to something special on your birthday – you deserve it!",
        "Happy Birthday to one of my favorite people on the planet.",
        "Getting older sucks, but you make it look easy.",
        "You make life more fun for everyone you meet. Thanks for being you.",
        "You do so much for others, I hope you find time to do something for yourself on your birthday.",
        "Your birthday’s here! Another year! Have good cheer! Grab a beer!",
        "I hope everyone remembers your birthday, but forgets how old you are.",
        "Congratulations on another year on Earth.",
        "There’s something in the air today… I think it’s an old fart.",
        "I’d tell you to spoil yourself today, but you’re already pretty rotten!",
        "Have a great birthday, and remember to never act your age.",
        "Older, wiser, AND sexier? You’re doing something right, [girl/boy].",
        "You’re going to need a bigger cake for all those candles!",
        "Cheer up. Turning a year older is better than the alternative.",
        "Remember, you can get away with anything when it’s your birthday.",
        "If you get even half the birthday presents you deserve, I’ll come save you. Because you’ll be drowning in them.",
        "Here’s hoping you have a birthday that’s as special and wonderful as you are.",
        "I’m so grateful you were born on this day [age] years ago. It’s like a holiday for me!",
        "There’s not enough room on the planet for all the birthday presents you deserve.",
        "Happy Birthday to someone who just gets better and better with age.",
        "I’m celebrating today. It’s the anniversary of my favorite person being born.",
        "Happy Birthday to someone who’s absolutely, positively indispensable to me.",
        "If being awesome were a crime, you’d be on the top of the Most Wanted list. Happy Birthday!",
        "Wishing my BFF an FFB (Effing Fantastic Birthday).",
        "Happy Birthday to one of the awesomest people who ever lived.",
        "Hope you have an awesome day! The best boyfriend ever deserves the best birthday ever!",
        "Sending you birthday wishes, hugs, and kisses.",
        "Happy Birthday to the man I love. You deserve everything life has to offer.",
        "Lots of love to my birthday beau."
    ]
}
